spring:
  application:
    name: hr-demo
  devtools:
    restart:
      enabled: true
  messages:
    basename: "i18n/messages, config.i18n.messages"

  datasource:
    url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_SERVICE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
      separator: "/"

server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){faint} %clr(%5p) %clr(%-29.29logger{29}){cyan}: %msg%n"
  file:
    name: ${logging.file.path}/hr-demo.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include:
          - "*"
