_compile-p1:
    javac -d bin $(find Project1 -name "*.java")

# Run project 1 (Mini banking system)
run-p1 +args="Project1/accounts.csv": _compile-p1
    java -cp ./bin Project1.Main {{ args }}

_compile-p2:
    javac -d bin $(find Project2 -name "*.java")

# Run Project 2 (Http server)
run-p2: _compile-p2
    java -cp ./bin Project2.Main


[default]
run:
    just -l

clean:
    rm -rf bin/
