#!/bin/bash
set -euo pipefail
sqlplus -s / as sysdba <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE;
ALTER SESSION SET CONTAINER = FREEPDB1;
DECLARE
	v_count NUMBER;
BEGIN
	SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = UPPER('${ORACLE_APP_USER}');
	IF v_count = 0 THEN
		EXECUTE IMMEDIATE 'CREATE USER ${ORACLE_APP_USER} IDENTIFIED BY "${ORACLE_APP_PWD}"';
		EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO ${ORACLE_APP_USER}';
	END IF;
END;
/
EXIT;
SQL