package Project2;

public abstract class Employee {
	protected String name;
	protected final String id;
	protected double baseSalary;

	protected Employee(String name, String id, double salary) {
		this.name = name;
		this.baseSalary = salary;
		this.id = id;
	}

	public abstract double calculateSalary();

	public String toString() {
		String out = "Employee: " + name + " with ID: " + id + " and salary: " + calculateSalary();
		return out;
	}

	// generated by vscode ide:

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		long temp;
		temp = Double.doubleToLongBits(baseSalary);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Employee other = (Employee) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (Double.doubleToLongBits(baseSalary) != Double.doubleToLongBits(other.baseSalary))
			return false;
		return true;
	}

}
